@extends('layouts.staff')
@section('title', 'File Complaint Report')

@section('content')

{{-- Page Header --}}
<div class="flex items-center gap-3 mb-6">
    <a href="{{ route('staff.blotter.index') }}"
       class="flex h-8 w-8 items-center justify-center rounded-xl border border-gray-200 bg-white text-gray-400 hover:text-gray-600 hover:border-gray-300 transition-all shadow-sm">
        <i class="fa-solid fa-arrow-left text-xs"></i>
    </a>
    <div>
        <h2 class="text-base font-semibold text-gray-900">File Complaint Report</h2>
        <p class="text-xs text-gray-400 mt-0.5">Complete the form — the case will be submitted for official review</p>
    </div>
</div>

<form action="{{ route('staff.blotter.store') }}" method="POST">
@csrf

<div class="grid grid-cols-1 xl:grid-cols-3 gap-5">

    {{-- Left Column --}}
    <div class="xl:col-span-2 space-y-5">

        {{-- Case Information --}}
        <div class="rounded-2xl bg-white border border-gray-100 shadow-sm overflow-hidden">
            <div class="flex items-center gap-3 px-5 py-4 border-b border-gray-100">
                <div class="flex h-7 w-7 items-center justify-center rounded-lg bg-red-50 text-red-500 text-xs">
                    <i class="fa-solid fa-shield-halved"></i>
                </div>
                <p class="text-sm font-semibold text-gray-800">Case Information</p>
            </div>
            <div class="p-5 grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                    <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">Case Number</label>
                    <input type="text" name="case_number" value="2024-017" readonly
                           class="w-full rounded-xl border border-gray-200 bg-gray-100 px-3.5 py-2.5 text-sm text-gray-400 cursor-not-allowed font-mono">
                    <p class="text-[11px] text-gray-400 mt-1">Auto-generated by the system</p>
                </div>
                <div>
                    <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">
                        Date of Incident <span class="text-red-500 normal-case font-normal">*</span>
                    </label>
                    <input type="date" name="incident_date" value="{{ old('incident_date') }}"
                           class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                  focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all" required>
                </div>
                <div>
                    <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">Time of Incident</label>
                    <input type="time" name="incident_time" value="{{ old('incident_time') }}"
                           class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                  focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all">
                </div>
                <div>
                    <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">
                        Incident Type <span class="text-red-500 normal-case font-normal">*</span>
                    </label>
                    <select name="incident_type"
                            class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                   focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all" required>
                        <option value="">Select type...</option>
                        <option {{ old('incident_type')=='Noise Complaint' ? 'selected' : '' }}>Noise Complaint</option>
                        <option {{ old('incident_type')=='Physical Altercation' ? 'selected' : '' }}>Physical Altercation</option>
                        <option {{ old('incident_type')=='Property Dispute' ? 'selected' : '' }}>Property Dispute</option>
                        <option {{ old('incident_type')=='Theft' ? 'selected' : '' }}>Theft</option>
                        <option {{ old('incident_type')=='Domestic' ? 'selected' : '' }}>Domestic</option>
                        <option {{ old('incident_type')=='Others' ? 'selected' : '' }}>Others</option>
                    </select>
                </div>
                <div class="sm:col-span-2">
                    <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">
                        Location of Incident <span class="text-red-500 normal-case font-normal">*</span>
                    </label>
                    <input type="text" name="location" value="{{ old('location') }}"
                           placeholder="e.g. Purok 3, near the covered court"
                           class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                  focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all placeholder-gray-400" required>
                </div>
            </div>
        </div>

        {{-- Complainant & Respondent --}}
        <div class="rounded-2xl bg-white border border-gray-100 shadow-sm overflow-hidden">
            <div class="flex items-center gap-3 px-5 py-4 border-b border-gray-100">
                <div class="flex h-7 w-7 items-center justify-center rounded-lg bg-blue-50 text-blue-500 text-xs">
                    <i class="fa-solid fa-people-arrows"></i>
                </div>
                <p class="text-sm font-semibold text-gray-800">Parties Involved</p>
            </div>
            <div class="p-5 grid grid-cols-1 sm:grid-cols-2 gap-5">

                {{-- Complainant --}}
                <div class="space-y-3">
                    <p class="text-xs font-bold text-gray-700 uppercase tracking-wide flex items-center gap-1.5">
                        <span class="inline-flex items-center justify-center h-4 w-4 rounded-full bg-blue-100 text-blue-600 text-[9px] font-bold">C</span>
                        Complainant
                    </p>
                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Full Name <span class="text-red-500">*</span></label>
                        <input type="text" name="complainant_name" value="{{ old('complainant_name') }}"
                               placeholder="Full name of complainant"
                               class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                      focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all placeholder-gray-400" required>
                    </div>
                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Address</label>
                        <input type="text" name="complainant_address" value="{{ old('complainant_address') }}"
                               placeholder="Purok / Street address"
                               class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                      focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all placeholder-gray-400">
                    </div>
                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Contact Number</label>
                        <input type="tel" name="complainant_contact" value="{{ old('complainant_contact') }}"
                               placeholder="09xx-xxx-xxxx"
                               class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                      focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all placeholder-gray-400">
                    </div>
                </div>

                {{-- Respondent --}}
                <div class="space-y-3">
                    <p class="text-xs font-bold text-gray-700 uppercase tracking-wide flex items-center gap-1.5">
                        <span class="inline-flex items-center justify-center h-4 w-4 rounded-full bg-red-100 text-red-600 text-[9px] font-bold">R</span>
                        Respondent
                    </p>
                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Full Name <span class="text-red-500">*</span></label>
                        <input type="text" name="respondent_name" value="{{ old('respondent_name') }}"
                               placeholder="Full name of respondent"
                               class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                      focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all placeholder-gray-400" required>
                    </div>
                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Address</label>
                        <input type="text" name="respondent_address" value="{{ old('respondent_address') }}"
                               placeholder="Purok / Street address"
                               class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                      focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all placeholder-gray-400">
                    </div>
                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Contact Number</label>
                        <input type="tel" name="respondent_contact" value="{{ old('respondent_contact') }}"
                               placeholder="09xx-xxx-xxxx"
                               class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                      focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all placeholder-gray-400">
                    </div>
                </div>
            </div>
        </div>

        {{-- Incident Details --}}
        <div class="rounded-2xl bg-white border border-gray-100 shadow-sm overflow-hidden">
            <div class="flex items-center gap-3 px-5 py-4 border-b border-gray-100">
                <div class="flex h-7 w-7 items-center justify-center rounded-lg bg-gray-100 text-gray-500 text-xs">
                    <i class="fa-solid fa-file-lines"></i>
                </div>
                <p class="text-sm font-semibold text-gray-800">Incident Details</p>
            </div>
            <div class="p-5 space-y-4">
                <div>
                    <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">
                        Narrative / Description <span class="text-red-500 normal-case font-normal">*</span>
                    </label>
                    <textarea name="narrative" rows="4"
                              placeholder="Describe the incident in detail — what happened, when, how it started..."
                              class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                     focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all placeholder-gray-400 resize-none" required>{{ old('narrative') }}</textarea>
                </div>
                <div>
                    <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">Witnesses (optional)</label>
                    <input type="text" name="witnesses" value="{{ old('witnesses') }}"
                           placeholder="Names of witnesses, separated by commas"
                           class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                  focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all placeholder-gray-400">
                </div>
                <div>
                    <label class="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1.5">Initial Action Taken</label>
                    <textarea name="action_taken" rows="2"
                              placeholder="Describe any immediate action taken by the staff..."
                              class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                                     focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all placeholder-gray-400 resize-none">{{ old('action_taken') }}</textarea>
                </div>
            </div>
        </div>

    </div>

    {{-- Right Column --}}
    <div class="space-y-5">

        {{-- Submit Card --}}
        <div class="rounded-2xl bg-white border border-gray-100 shadow-sm overflow-hidden">
            <div class="flex items-center gap-3 px-5 py-4 border-b border-gray-100">
                <div class="flex h-7 w-7 items-center justify-center rounded-lg bg-red-50 text-red-500 text-xs">
                    <i class="fa-solid fa-paper-plane"></i>
                </div>
                <p class="text-sm font-semibold text-gray-800">Submit Case</p>
            </div>
            <div class="p-5 space-y-3">
                <button type="submit"
                        class="w-full flex items-center justify-center gap-2 rounded-xl py-2.5 text-sm font-semibold text-white bg-red-600 hover:bg-red-700 transition-colors">
                    <i class="fa-solid fa-paper-plane text-xs"></i> Submit for Official Review
                </button>
                <a href="{{ route('staff.blotter.index') }}"
                   class="w-full flex items-center justify-center gap-2 rounded-xl py-2.5 text-sm font-semibold text-gray-600 bg-gray-100 hover:bg-gray-200 transition-colors">
                    Cancel
                </a>
                <p class="text-[11px] text-gray-400 text-center leading-relaxed">
                    The case will be set to <strong class="text-amber-600">Pending Official</strong> until reviewed by the Barangay Captain or authorized official.
                </p>
            </div>
        </div>

        {{-- Case Status --}}
        <div class="rounded-2xl bg-white border border-gray-100 shadow-sm overflow-hidden">
            <div class="flex items-center gap-3 px-5 py-4 border-b border-gray-100">
                <div class="flex h-7 w-7 items-center justify-center rounded-lg bg-amber-50 text-amber-500 text-xs">
                    <i class="fa-solid fa-tags"></i>
                </div>
                <p class="text-sm font-semibold text-gray-800">Initial Status</p>
            </div>
            <div class="p-5">
                <select name="initial_status"
                        class="w-full rounded-xl border border-gray-200 bg-gray-50 px-3.5 py-2.5 text-sm text-gray-900
                               focus:border-green-600 focus:ring-2 focus:ring-green-600/20 focus:bg-white focus:outline-none transition-all">
                    <option value="Pending Official" selected>Pending Official</option>
                    <option value="Open">Open (No approval needed)</option>
                </select>
                <p class="text-[11px] text-gray-400 mt-2">
                    Cases requiring mediation or referral must go through official approval.
                </p>
            </div>
        </div>

        {{-- Reminders --}}
        <div class="rounded-2xl border border-blue-100 bg-blue-50 p-4">
            <p class="text-xs font-semibold text-blue-700 mb-2 flex items-center gap-1.5">
                <i class="fa-solid fa-lightbulb"></i> Reminders
            </p>
            <ul class="text-xs text-blue-600 space-y-1.5 list-disc list-inside">
                <li>Ensure all required fields are complete before submitting.</li>
                <li>Both parties must be notified once a case is filed.</li>
                <li>The official will be notified automatically upon submission.</li>
                <li>Cases returned with remarks must be corrected and resubmitted.</li>
            </ul>
        </div>

        {{-- Approval Flow Info --}}
        <div class="rounded-2xl border border-amber-100 bg-amber-50 p-4">
            <p class="text-xs font-semibold text-amber-700 mb-3 flex items-center gap-1.5">
                <i class="fa-solid fa-diagram-project"></i> Approval Flow
            </p>
            <div class="space-y-2">
                @php
                    $steps = [
                        ['label' => 'Staff Files Report',       'icon' => 'fa-pen-to-square', 'active' => true],
                        ['label' => 'Submitted for Review',     'icon' => 'fa-paper-plane',   'active' => false],
                        ['label' => 'Official Reviews Case',    'icon' => 'fa-user-tie',       'active' => false],
                        ['label' => 'Decision & Action',        'icon' => 'fa-gavel',          'active' => false],
                    ];
                @endphp
                @foreach($steps as $i => $step)
                <div class="flex items-center gap-2.5">
                    <div class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full {{ $step['active'] ? 'bg-amber-500 text-white' : 'bg-white border border-amber-200 text-amber-400' }} text-[10px]">
                        @if($step['active'])
                            <i class="fa-solid {{ $step['icon'] }}"></i>
                        @else
                            <span class="font-bold">{{ $i + 1 }}</span>
                        @endif
                    </div>
                    <span class="text-xs {{ $step['active'] ? 'font-semibold text-amber-800' : 'text-amber-600' }}">
                        {{ $step['label'] }}
                    </span>
                </div>
                @if(!$loop->last)
                <div class="ml-3 h-3 w-px bg-amber-200"></div>
                @endif
                @endforeach
            </div>
        </div>

    </div>
</div>

</form>

@endsection
